# Day 12

# Numpy Library Part 1

In [3]:
import numpy as np
arr = np.array( [ 1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimensions in Array

In [4]:
arr = np.array(20)
print(arr)
print(type(arr))

20
<class 'numpy.ndarray'>


In [5]:
print(arr.ndim)

0


# 1d array

In [6]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


# 2d array

In [7]:
arr = np.array([[1,2,3],[1,2,3]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>
2


In [8]:
arr = np.array([[1.3,2.4,3.8],[1.9,2.7,3.6]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1.3 2.4 3.8]
 [1.9 2.7 3.6]]
<class 'numpy.ndarray'>
2


# 3d array
# Anarray that has 2-d arrays (matrices)as its elements is called a 3-d array

In [10]:
arr = np.array([[[1.3,2.4,3.8],[4,5,6]],[[1.9,2.7,3.6],[1,2,3]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[1.3 2.4 3.8]
  [4.  5.  6. ]]

 [[1.9 2.7 3.6]
  [1.  2.  3. ]]]
<class 'numpy.ndarray'>
3


# Check number of dimensions

In [11]:
a = np.array(42)
b = np.array([1,2,3,4])
c = np.array([[1,2,3,4],[1,2,3,4]])
d = np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimension Arrays
# An array can have any number of dimensions.When the array is created,you can define the no.of dimensions by usig the n.dim argument 

# Create an array with 5 dimensions and verify that it has 5 dimensions

In [9]:
import numpy as np
arr = np.array([1,2,3,4,5],ndmin = 5)
print(arr)
print("Number of Dimensions"  ,arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number of Dimensions 5


In [10]:
a = np.array( [[[[[ 1,2,3,4]]]]])
print(a)
print(a.ndim)
     

[[[[[1 2 3 4]]]]]
5


# Numpy Array Indexing

 Array Indexing is the same as accessing an array element.
You can access an array element by referring to its index numbers.
The index in numpy starts with 0 ,meaning that the first element has index 0, and the second has 1 etc.

# Get the first element from the following array

In [13]:
arr = np.array([1,2,3,4])
print(arr[0])

1


# Get third,sixth and eighth elements from the following array and add them

In [7]:
import numpy as np

m = np.array([41,87,34,56,39,90,15,10,19,56])
print( "The second element is", m[2])
print( "The sixth element is", m[5])
print( "The eighth element is ", m[7])
print( "The sum of these elements is ",(m[2]+m[7]+m[5]))

The second element is 34
The sixth element is 90
The eighth element is  10
The sum of these elements is  134


# Access 2-d arrays
# To access elements from 2-d arrays we can use coma separated integers representing the dimension and the index of the element

In [8]:
import numpy as np
arr = np.array ([[10,20,30,40,50],[60,70,80,90,100]])
print('Second element on Ist row: ', arr[0,1])
print('Fourth element on Ist row: ', arr[0,3])
print('First element on 2nd row : ',arr[1,0])
print('Last element on 2nd row  : ', arr[1,4])
print("Sum is"  , arr[0,1]+arr[0,3]+ arr[1,0]+ arr[1,4])
print(arr[0,2])
print(arr[1,3])

Second element on Ist row:  20
Fourth element on Ist row:  40
First element on 2nd row :  60
Last element on 2nd row  :  100
Sum is 220
30
90


# Access 3-d arrays

# To access elements from 3-d arrays we can use comma separated integers representing the dimensions and the index position of the element
# Access the third element of the second array of the first array

In [4]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [5]:
print(arr[1,1,2])

12


In [6]:
print(arr[1,0,1])

8


In [7]:
print(arr[1,1,0])

10
